### ISSUE TITLE
Add Kalnia Glaze and Bunge Tint

### ISSUE THREAD

**Issue by vv-monsalve** [Lorp/figma-colrv1#15]
After installing the plugin in a new machine and have a question plus a suggestion.

**Q:** Could it be possible to drop a font?

**S:** We have released in GF now Bungee Color as [Bunge Tint](https://fonts.google.com/specimen/Bungee+Tint) and a new COLRv1 font called [Kalnia Glaze](https://fonts.google.com/specimen/Kalnia+Glaze). It would be fantastic if they are included in the tool. I mean Bunge Color updated to the Tint version ;)

**Comment by Lorp** [comment]
This is fixed now.

Dropping a font: just drop it onto the UI! (I should make that clearer, at least when the font is over the UI window.)
