### ISSUE TITLE
Could changing the font take effect as soon as the new one is picked?

### ISSUE THREAD

**Issue by vv-monsalve** [Lorp/figma-colrv1#8]
When selecting a new font, it doesn't appear to take effect. It takes a couple of secs and it only takes effect until the user also changes the text or hits `cmnd + z`, but this changes the word.

https://github.com/Lorp/figma-colrv1/assets/48698976/45c414b3-17a8-41ef-b191-e263f648b1e0

**Comment by Lorp** [comment]
Indeed, this is a bug and I'll fix it.

**Comment by Lorp** [comment]
Fixed in #12
